import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is defined explicitly rather than autogenerated, so the reading
 * order is deliberate: what the library is, how to install it, one guide per
 * concern, then a reference of the public API surface.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: ['getting-started/installation', 'getting-started/quick-start'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/configuration',
        'guides/making-requests',
        'guides/versioning',
        'guides/error-handling',
        'guides/retry',
        'guides/success-messages',
        'guides/loading-state',
        'guides/testing',
      ],
    },
    {
      type: 'category',
      label: 'API reference',
      collapsed: false,
      items: [
        'api/provide-api',
        'api/api-service',
        'api/api-loading-service',
        'api/interceptors',
        'api/handlers',
        'api/models',
        'api/tokens',
      ],
    },
  ],
};

export default sidebars;
